services:
  service.rest:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+
    ports:
      - "${SERVICE_REST_PORT}:80"

  aichatdb:
    container_name: aichatdb
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:${POSTGRES_VOLUME_PATH}